"""initial_schema

Revision ID: 8500ec08dd91
Revises: 
Create Date: 2026-05-24 17:04:56.060797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8500ec08dd91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('short_code', sa.String(length=5), nullable=True),
    sa.Column('category', sa.String(length=20), server_default='non_african', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country'), 'country', ['country'], unique=True)
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_index(op.f('ix_country_short_code'), 'country', ['short_code'], unique=True)
    op.create_table('org_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('project', 'department', 'college', 'secretariat', 'other', name='orgunittype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_unit_id'), 'org_unit', ['id'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=45), nullable=False),
    sa.Column('permission_code', sa.String(length=45), nullable=False),
    sa.Column('system_code', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_index('ix_permission', 'permission', ['permission', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_index('ix_role', 'role', ['role', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_user', 'user', ['deleted_at', 'email', 'phone', 'id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('account_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verification_token', sa.String(255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_verification', 'account_verification', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_account_verification_id'), 'account_verification', ['id'], unique=False)
    op.create_index(op.f('ix_account_verification_verification_token'), 'account_verification', ['verification_token'], unique=True)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(255), nullable=False),
    sa.Column('target', sa.String(255), nullable=True),
    sa.Column('ip_address', sa.String(255), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log', 'activity_log', ['action', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('banner_image', sa.Text(), nullable=True),
    sa.Column('organizers', sa.Text(), nullable=True),
    sa.Column('participation_info', sa.Text(), nullable=True),
    sa.Column('logistics_info', sa.Text(), nullable=True),
    sa.Column('sponsors_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('organisation', sa.String(length=200), nullable=False),
    sa.Column('organisation_type', sa.Enum('Non_profit', 'Corporation', 'Government', 'Other', name='organisationtype'), nullable=False),
    sa.Column('sector', sa.Enum('Technology', 'Education', 'Healthcare', 'Finance', 'Other', name='sectortype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_donor', sa.Boolean(), nullable=True),
    sa.Column('is_recipient', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation', 'country_id', name='uix_organisation_country')
    )
    op.create_index('ix_organisation_country', 'organisation', ['organisation', 'country_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_organisation_id'), 'organisation', ['id'], unique=False)
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reset_token', sa.String(255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset', 'password_reset', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_password_reset_id'), 'password_reset', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_reset_token'), 'password_reset', ['reset_token'], unique=True)
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='role_id_permission_id')
    )
    op.create_index('ix_role_permission', 'role_permission', ['role_id', 'permission_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_role_permission_id'), 'role_permission', ['id'], unique=False)
    op.create_table('user_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_photo', 'user_photo', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_user_photo_id'), 'user_photo', ['id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('organisation', sa.String(length=200), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_profile', 'user_profile', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='user_id_role_id')
    )
    op.create_index('ix_user_role', 'user_role', ['user_id', 'role_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.create_table('abstract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract_text', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('track', sa.String(length=200), nullable=True),
    sa.Column('presentation_type', sa.Enum('oral', 'poster', 'either', name='presentationtype'), server_default='either', nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'accepted', 'rejected', 'revision_required', name='abstractstatus'), server_default='submitted', nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_abstract', 'abstract', ['event_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_abstract_id'), 'abstract', ['id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('ProgrammeBooklet', 'Presentation', 'Photo', 'Advert', 'Guidelines', 'Other', name='documenttype'), nullable=False),
    sa.Column('file_type', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('access_level', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document', 'document', ['document_type', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_id'), 'link', ['id'], unique=False)
    op.create_table('organisation_approval_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Enum('Pending', 'Approved', 'Denied', name='organisationstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organisation_approval_status', 'organisation_approval_status', ['organisation_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_organisation_approval_status_id'), 'organisation_approval_status', ['id'], unique=False)
    op.create_table('organisation_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('ProgrammeBooklet', 'Presentation', 'Photo', 'Advert', 'Guidelines', 'Other', name='documenttype'), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organisation_document', 'organisation_document', ['document_type', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_organisation_document_id'), 'organisation_document', ['id'], unique=False)
    op.create_table('organisation_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=45), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('founders', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index('ix_organisation_registration', 'organisation_registration', ['registration_number', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_organisation_registration_id'), 'organisation_registration', ['id'], unique=False)
    op.create_table('organisation_verification_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organisation_verification_request', 'organisation_verification_request', ['organisation_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_organisation_verification_request_id'), 'organisation_verification_request', ['id'], unique=False)
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participation_role', sa.Enum('secretariat', 'delegate', 'presenter', 'speaker', 'sponsor', 'moderator', 'participant', 'student', 'exhibitor', 'world', 'other_africa', 'member_state', 'moh', name='participationrole'), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('payment_proof', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='unique_user_event_registration')
    )
    op.create_index(op.f('ix_registration_id'), 'registration', ['id'], unique=False)
    op.create_table('abstract_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('affiliation', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_presenting', sa.Boolean(), nullable=True),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstract.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abstract_author_id'), 'abstract_author', ['id'], unique=False)
    op.create_table('abstract_reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstract.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abstract_id', 'reviewer_id', name='unique_abstract_reviewer')
    )
    op.create_index(op.f('ix_abstract_reviewer_id'), 'abstract_reviewer', ['id'], unique=False)
    op.create_table('event_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'attendance_date', name='unique_event_attendance')
    )
    op.create_index(op.f('ix_event_attendance_id'), 'event_attendance', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MPESA', 'BANK_TRANSFER', 'CARD', name='paymentmethod'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', name='paymentstatus'), nullable=False),
    sa.Column('payment_receipt', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', name='unique_payment')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_table('abstract_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('methodology_score', sa.Integer(), nullable=False),
    sa.Column('originality_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('accept', 'reject', 'revision_required', name='reviewrecommendation'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('confidential_comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['abstract_reviewer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_index(op.f('ix_abstract_review_id'), 'abstract_review', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abstract_review_id'), table_name='abstract_review')
    op.drop_table('abstract_review')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_event_attendance_id'), table_name='event_attendance')
    op.drop_table('event_attendance')
    op.drop_index(op.f('ix_abstract_reviewer_id'), table_name='abstract_reviewer')
    op.drop_table('abstract_reviewer')
    op.drop_index(op.f('ix_abstract_author_id'), table_name='abstract_author')
    op.drop_table('abstract_author')
    op.drop_index(op.f('ix_registration_id'), table_name='registration')
    op.drop_table('registration')
    op.drop_index(op.f('ix_organisation_verification_request_id'), table_name='organisation_verification_request')
    op.drop_index('ix_organisation_verification_request', table_name='organisation_verification_request')
    op.drop_table('organisation_verification_request')
    op.drop_index(op.f('ix_organisation_registration_id'), table_name='organisation_registration')
    op.drop_index('ix_organisation_registration', table_name='organisation_registration')
    op.drop_table('organisation_registration')
    op.drop_index(op.f('ix_organisation_document_id'), table_name='organisation_document')
    op.drop_index('ix_organisation_document', table_name='organisation_document')
    op.drop_table('organisation_document')
    op.drop_index(op.f('ix_organisation_approval_status_id'), table_name='organisation_approval_status')
    op.drop_index('ix_organisation_approval_status', table_name='organisation_approval_status')
    op.drop_table('organisation_approval_status')
    op.drop_index(op.f('ix_link_id'), table_name='link')
    op.drop_index('ix_document', table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index('ix_document', table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_abstract_id'), table_name='abstract')
    op.drop_index('ix_abstract', table_name='abstract')
    op.drop_table('abstract')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_index('ix_user_role', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_index('ix_user_profile', table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_photo_id'), table_name='user_photo')
    op.drop_index('ix_user_photo', table_name='user_photo')
    op.drop_table('user_photo')
    op.drop_index(op.f('ix_role_permission_id'), table_name='role_permission')
    op.drop_index('ix_role_permission', table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_password_reset_reset_token'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_id'), table_name='password_reset')
    op.drop_index('ix_password_reset', table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_index(op.f('ix_organisation_id'), table_name='organisation')
    op.drop_index('ix_organisation_country', table_name='organisation')
    op.drop_table('organisation')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_index('ix_activity_log', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_account_verification_verification_token'), table_name='account_verification')
    op.drop_index(op.f('ix_account_verification_id'), table_name='account_verification')
    op.drop_index('ix_account_verification', table_name='account_verification')
    op.drop_table('account_verification')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index('ix_user', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index('ix_role', table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index('ix_permission', table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_org_unit_id'), table_name='org_unit')
    op.drop_table('org_unit')
    op.drop_index(op.f('ix_country_short_code'), table_name='country')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_index(op.f('ix_country_country'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
